### ISSUE TITLE
Display actual outline when Highlight outline is enabled

### ISSUE THREAD

**Issue by Z7-z** [Mafham/mafham-plugins#1]
Currently when you enable 'Highlight outline' it seems to highlight what I believe is the hull, but when you enable 'Hull highlight' it's also the hull, but filled in. 

I will provide two screenshots the first screenshot is this plugin with outline enabled, the second screenshot is from other NPC plugins with their outline option enabled, it seems every other plugin highlights outlines in this way, and in my opinion looks alot more proper, since it is truly the NPC's outline.

1st: https://i.imgur.com/m13pUEy.png
2nd: https://i.imgur.com/mMrNZl6.png

**Comment by Z7-z** [comment]
saw [#4751](https://github.com/runelite/plugin-hub/pull/4751) i was also going to ask for a filter too! excellent work!

**Comment by Mafham** [comment]
Thanks 😄
